-- Profiles schema removed
-- This SQL previously created the `public.profiles` table and a trigger to
-- synchronize `auth.users` -> `public.profiles`. Supabase integration has been
-- removed from this project; keep this file for reference only.
