-- Supabase schema removed from project
-- This file remains in the repository for reference only. The project
-- currently runs without Supabase; if you need to re-enable Supabase,
-- restore or replace this schema and reconfigure the environment.
